minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true


verifyDepsBeforeRun: false
verifyStoreIntegrity: true
strictSsl: true
strictDepBuilds: true
ignoreScripts: true
blockExoticSubdeps: true
resolutionMode: time-based
dangerouslyAllowAllBuilds: false 
savePrefix: ''

trustPolicy: no-downgrade

ignoredOptionalDependencies:
- "@typescript/*"
- "@esbuild/*"
- "@biomejs/*"

packages:
  - src
  - '!**/test/**'

dedupeInjectedDeps: false

peerDependencyRules:
  ignoreMissing:
  - "@types/react"